from datetime import time

AFTERNOON_START = time(14, 0)
AFTERNOON_END = time(16, 0)
ROUND_DOLLAR_POINTS = 50
MULTIPLE_OF_025_POINTS = 25
ITEMS_PAIR_POINTS = 5
ODD_DAY_POINTS = 6
AFTERNOON_PURCHASE_POINTS = 10
